apiVersion: v1
kind: ReplicationController
metadata:
  name: rolling
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rolling-test
        image: nginx
        ports:
        - containerPort: 80
