apiVersion: v1
kind: ReplicationController
metadata:
  name: rolling-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rolling-test
        image: nginx
        command:
         - "sleep"
         - "1000"
        ports:
         - containerPort: 80
      - name: sec-rolling-test
        image: ubuntu
        command:
         - "sleep"
         - "1000"
        ports:
         - containerPort: 80
