apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ok
            port: 80
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
