kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: html-disk
  annotations: 
    volume.beta.kubernetes.io/storage-class: "generic" 
spec: 
  accessModes: 
    - "ReadWriteOnce" 
  resources: 
    requests: 
      storage: "10Gi"
