apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html"
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: html-disk
