apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrettest
  template:
    metadata:
      labels:
        app: secrettest
    spec:
      containers:
        - image: nginx
          name: nginx-server
          ports:
            - containerPort: 80
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: thesecret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: thesecret
                  key: password       
